<?php
/**
 * Central configuration bootstrap.
 * Loads .env, starts the session, and exposes a config() helper.
 */

// Ensure dependencies are installed (vendor/autoload.php)
$autoload = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
} else {
    http_response_code(500);
    echo "Project dependencies are missing.\n";
    echo "Run `composer install` in the project root (A:\\laragon\\www\\SP3).\n";
    echo "If PHP is not in PATH, run the installer with your php.exe, for example:\n";
    echo "\"A:\\\\laragon\\\\bin\\\\php\\\\php-<version>\\\\php.exe\" composer.phar install\n";
    exit;
}

/** @noinspection PhpUndefinedClassInspection */
use Dotenv\Dotenv;

// Auto-create .env from .env.example if missing (convenience for local dev)
$envFile = __DIR__ . '/..' . '/.env';
$envExample = __DIR__ . '/..' . '/.env.example';
if (!file_exists($envFile) && file_exists($envExample)) {
    copy($envExample, $envFile);
}

// Guard Dotenv usage so startup doesn't fatal when vendor isn't yet installed.
if (class_exists(\Dotenv\Dotenv::class)) {
    $dotenv = Dotenv::createImmutable(__DIR__ . '/..');
    $dotenv->safeLoad();
} else {
    // Intelephense/static analysis may still report missing type until
    // `composer install` runs; we already printed a helpful message earlier.
}

// ---- Session ----
// Detect HTTPS the same way base_url() does, so the cookie's Secure flag
// tracks the actual connection instead of assuming local HTTP forever.
$isHttps = ($_SERVER['HTTPS'] ?? '') !== '' && ($_SERVER['HTTPS'] ?? '') !== 'off';

$sessionName = $_ENV['SESSION_NAME'] ?? 'stockpilot_session';
$sessionLifetime = (int) ($_ENV['SESSION_LIFETIME'] ?? 1800); // seconds of inactivity before auto-logout

if (session_status() === PHP_SESSION_NONE) {
    session_name($sessionName);
    session_set_cookie_params([
        'lifetime' => 0,          // expires when the browser closes
        'path'     => '/',
        'domain'   => '',
        'secure'   => $isHttps,   // never send the cookie over plain HTTP once deployed on HTTPS
        'httponly' => true,       // JavaScript can never read the session cookie
        'samesite' => 'Lax',      // blocks the cookie being sent on cross-site POSTs (CSRF defense-in-depth)
    ]);
    session_start();

    // Idle timeout: if the session has been quiet too long, treat it as
    // expired rather than trusting an old authenticated cookie forever.
    if (isset($_SESSION['_last_activity']) && (time() - $_SESSION['_last_activity']) > $sessionLifetime) {
        $_SESSION = [];
        session_destroy();
        session_start();
    }
    $_SESSION['_last_activity'] = time();

    // Session fixation guard: if this session was never regenerated by
    // Auth::login(), rotate its ID periodically anyway.
    if (!isset($_SESSION['_started_at'])) {
        $_SESSION['_started_at'] = time();
    } elseif (Auth_shouldRegenerate($_SESSION['_started_at'])) {
        session_regenerate_id(true);
        $_SESSION['_started_at'] = time();
    }
}

function Auth_shouldRegenerate(int $startedAt): bool
{
    return (time() - $startedAt) > 900; // rotate the session ID every 15 minutes
}

// ---- Error display ----
if (($_ENV['APP_DEBUG'] ?? 'false') === 'true') {
    ini_set('display_errors', '1');
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', '0');
    error_reporting(0);
}

// ---- Security headers (sent on every response, HTML or JSON) ----
// CSP allows 'unsafe-inline' for script/style because the existing views
// use inline <script> blocks and inline style="" attributes throughout —
// flipping to a strict nonce-based CSP would mean touching every view.
// This is documented as a known trade-off in SECURITY_AUDIT.md rather
// than silently claiming a stricter policy than what's actually enforced.
if (!headers_sent()) {
    header("X-Content-Type-Options: nosniff");
    header("X-Frame-Options: DENY");
    header("Referrer-Policy: strict-origin-when-cross-origin");
    header("Permissions-Policy: camera=(self), microphone=(), geolocation=(), payment=()");
    header(
        "Content-Security-Policy: default-src 'self'; " .
        "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; " .
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " .
        "font-src 'self' https://fonts.gstatic.com; " .
        "img-src 'self' data:; " .
        "connect-src 'self'; " .
        "frame-ancestors 'none'; " .
        "base-uri 'self'; " .
        "form-action 'self'"
    );
    if ($isHttps) {
        header("Strict-Transport-Security: max-age=31536000; includeSubDomains");
    }
}

/**
 * Fetch a config/env value with dot-free simple keys.
 */
function config(string $key, $default = null)
{
    return $_ENV[$key] ?? $default;
}

if (!function_exists('e')) {
    function e($value): string
    {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    }
}

/**
 * Base URL helper — used in views for asset/link paths.
 */
function base_url(string $path = ''): string
{
    $configured = config('APP_URL', '');

    $https = ($_SERVER['HTTPS'] ?? '') !== '' && ($_SERVER['HTTPS'] ?? '') !== 'off';
    $scheme = $https ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'] ?? 'localhost';
    $scriptName = $_SERVER['SCRIPT_NAME'] ?? '';
    $scriptDir = rtrim(str_replace('\\', '/', dirname($scriptName)), '/');
    $currentBase = sprintf('%s://%s%s', $scheme, $host, $scriptDir !== '' ? $scriptDir : '');

    if (!empty($configured)) {
        $configured = rtrim($configured, '/');
        $configuredUrl = parse_url($configured);
        $configuredHost = $configuredUrl['host'] ?? null;
        $configuredPath = rtrim($configuredUrl['path'] ?? '', '/');

        if ($configuredHost === $host && $configuredPath === $scriptDir) {
            $base = $configured;
        } else {
            $base = $currentBase;
        }
    } else {
        $base = $currentBase;
    }

    $base = rtrim($base, '/');
    return $base . '/' . ltrim($path, '/');
}
